// Admin rejection email preview page.
// Read-only. No send button. No forms. No approve/reject actions.
// CB Control Center makes enrollment decisions. MKCRM does not. Payment systems do not.
// Preview-only — no email has been sent.

import { getAllDapAdminRejectionEmailPreviews } from '@/lib/cb-control-center/dapAdminRejectionEmailPreview'

export default function AdminRejectionEmailsPreviewPage() {
  const previews = getAllDapAdminRejectionEmailPreviews()

  return (
    <main
      className="max-w-3xl mx-auto px-4 py-8 space-y-8"
      data-page-kind="admin_rejection_email_preview"
      data-implies-phi="false"
      data-implies-payment="false"
      data-preview-only="true"
      data-send-enabled="false"
    >
      {/* Header */}
      <div className="space-y-2">
        <p className="text-xs font-medium text-gray-400 uppercase tracking-wide">
          CB Control Center — Preview
        </p>
        <h1 className="text-xl font-semibold text-gray-900">Admin Rejection Email Previews</h1>
        <p className="text-sm text-gray-500">
          Preview-only. No emails have been sent. These templates are generated by CB Control Center.
          MKCRM has no decision authority. Client Builder Pro and payment systems have no authority
          over DAP enrollment decisions.
        </p>
      </div>

      {/* Authority boundary notice */}
      <div
        className="rounded-lg border border-blue-100 bg-blue-50 px-4 py-3 space-y-1"
        data-authority-notice
      >
        <p className="text-xs font-semibold text-blue-800 uppercase tracking-wide">
          Authority Boundary
        </p>
        <ul className="text-xs text-blue-700 space-y-0.5">
          <li>CB Control Center decides rejections</li>
          <li>MKCRM does not decide rejections</li>
          <li>Client Builder Pro / payment system does not decide rejections</li>
        </ul>
      </div>

      {/* Template previews */}
      <div className="space-y-6">
        {previews.map(preview => (
          <section
            key={preview.templateKey}
            className="rounded-lg border border-gray-200 bg-white p-6 space-y-4"
            data-template-key={preview.templateKey}
          >
            {/* Template header */}
            <div className="flex items-start justify-between gap-3 flex-wrap">
              <div className="space-y-1">
                <p className="text-xs font-mono text-gray-500">{preview.templateKey}</p>
                <p className="text-xs text-gray-400">
                  Audience: <span className="font-medium text-gray-600">{preview.copy.audience}</span>
                </p>
              </div>
              <div className="flex gap-2 flex-wrap">
                <span className="text-xs px-2 py-0.5 rounded bg-amber-50 border border-amber-200 text-amber-700 font-medium">
                  Preview only
                </span>
                <span className="text-xs px-2 py-0.5 rounded bg-gray-100 text-gray-500">
                  Not sent
                </span>
              </div>
            </div>

            {/* Email content */}
            <div className="space-y-3 border-t border-gray-100 pt-4">
              <div>
                <p className="text-xs font-medium text-gray-400 uppercase tracking-wide mb-0.5">Subject</p>
                <p className="text-sm text-gray-800">{preview.copy.subject}</p>
              </div>
              <div>
                <p className="text-xs font-medium text-gray-400 uppercase tracking-wide mb-0.5">Headline</p>
                <p className="text-sm font-semibold text-gray-900">{preview.copy.headline}</p>
              </div>
              <div>
                <p className="text-xs font-medium text-gray-400 uppercase tracking-wide mb-1">Body</p>
                <div className="space-y-1.5">
                  {preview.copy.body.map((para, i) => (
                    <p key={i} className="text-sm text-gray-700 leading-relaxed">{para}</p>
                  ))}
                </div>
              </div>
              <div className="border-t border-gray-100 pt-3">
                <p className="text-xs text-gray-400 italic">{preview.copy.footerNote}</p>
              </div>
            </div>

            {/* Delivery + safety flags */}
            <div className="grid grid-cols-2 gap-3 border-t border-gray-100 pt-4">
              <div className="rounded-md bg-gray-50 border border-gray-200 px-3 py-2 space-y-1">
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Delivery</p>
                <div className="text-xs font-mono space-y-0.5 text-gray-600">
                  <div>queued: <span className="text-green-700 font-semibold">false</span></div>
                  <div>scheduled: <span className="text-green-700 font-semibold">false</span></div>
                  <div>sent: <span className="text-green-700 font-semibold">false</span></div>
                  <div>dryRunOnly: <span className="text-green-700 font-semibold">true</span></div>
                </div>
              </div>
              <div className="rounded-md bg-gray-50 border border-gray-200 px-3 py-2 space-y-1">
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Safety</p>
                <div className="text-xs font-mono space-y-0.5 text-gray-600">
                  <div>includesPaymentCta: <span className="text-green-700 font-semibold">false</span></div>
                  <div>includesPhi: <span className="text-green-700 font-semibold">false</span></div>
                  <div>includesCta: <span className="text-green-700 font-semibold">false</span></div>
                  <div>previewOnly: <span className="text-green-700 font-semibold">true</span></div>
                </div>
              </div>
            </div>
          </section>
        ))}
      </div>
    </main>
  )
}
