import type { CbBusinessPortfolio } from './cbBusinessPortfolioTypes'

export const CB_BUSINESS_PORTFOLIO: CbBusinessPortfolio = {
  businesses: [
    {
      slug: 'dental-advantage-plan',
      name: 'Dental Advantage Plan',
      description:
        'Dental membership and savings directory for patients without traditional insurance.',
      category: 'Patient marketplace / directory',
      status: 'blocked',
      statusLabel: 'Blocked at Truth Schema',
      readinessPercent: 42,
      nextAction:
        'Resolve provider, offer, request flow, CTA gate, and declined routing blockers.',
      buildPath: '/businesses/dental-advantage-plan/build',
      detailPath: '/businesses/dental-advantage-plan',
      isActive: true,
    },
    {
      slug: 'client-builder-pro',
      name: 'Client Builder Pro',
      description: 'Market and payment brand for client acquisition.',
      category: 'Payment / client acquisition',
      status: 'foundation_active',
      statusLabel: 'Foundation active',
      readinessPercent: null,
      nextAction: 'Define relationship to DAP, MKCRM, and payment flows.',
      buildPath: null,
      detailPath: '/businesses/client-builder-pro',
      isActive: true,
    },
    {
      slug: 'renu-gut',
      name: 'RenuGut',
      description: 'Gut health research and content platform.',
      category: 'Health content / education',
      status: 'content_strategy_active',
      statusLabel: 'Content strategy active',
      readinessPercent: null,
      nextAction: 'Continue expert review and podcast guide workflow.',
      buildPath: null,
      detailPath: '/businesses/renu-gut',
      isActive: true,
    },
    {
      slug: 'pocons-usa',
      name: 'POCONS USA',
      description: 'Precision component manufacturer sales and outbound content system.',
      category: 'B2B sales / outbound',
      status: 'go_to_market_active',
      statusLabel: 'Go-to-market active',
      readinessPercent: null,
      nextAction: 'Continue newsletter and outbound authority strategy.',
      buildPath: null,
      detailPath: '/businesses/pocons-usa',
      isActive: true,
    },
    {
      slug: 'ai-digital-staffing',
      name: 'AI Digital Staffing',
      description: 'Newsletter and education platform for SMB AI automation.',
      category: 'Newsletter / SMB education',
      status: 'concept',
      statusLabel: 'Concept / content system',
      readinessPercent: null,
      nextAction: 'Define MVP publishing workflow.',
      buildPath: null,
      detailPath: '/businesses/ai-digital-staffing',
      isActive: false,
    },
  ],
  newBusinessAction: {
    label: 'Start New Business',
    path: '/businesses/new',
    description:
      'Create a new market, site, directory, content brand, SaaS workflow, or client system.',
  },
}
