// DAP admin rejection email copy.
// Copy is soft, neutral, and non-accusatory.
// CB Control Center makes enrollment decisions. MKCRM does not. Payment systems do not.
// Preview-only. No email sending. No PHI. No payment CTAs. No insurance-like language.

import type {
  DapAdminRejectionEmailTemplateKey,
  DapAdminRejectionEmailCopy,
} from './dapAdminRejectionEmailTypes'

// ─── Required footer note (locked language) ────────────────────────────────────

export const DAP_REJECTION_FOOTER_NOTE =
  'This is a preview of an administrative notification generated by CB Control Center. ' +
  'No email has been sent. MKCRM does not decide rejections. ' +
  'Client Builder Pro and payment systems have no authority over DAP enrollment decisions.'

// ─── Forbidden copy terms ─────────────────────────────────────────────────────

export const DAP_REJECTION_FORBIDDEN_TERMS: string[] = [
  'denied',
  'failed',
  'blacklisted',
  'fraud',
  'terminated',
  'charged',
  'payment required',
  'claim',
  'insurance',
  'coverage',
  'benefits',
  'hipaa',
  'diagnosis',
  'procedure',
  'treatment',
  'pay now',
  'update payment',
  'checkout',
  'billing portal',
  'mkcrm determines',
  'mkcrm has authority',
  'mkcrm decides',
  'patient health',
  'medical record',
  'date of birth',
  'social security',
]

// ─── Copy library ─────────────────────────────────────────────────────────────

const REJECTION_COPY: Record<DapAdminRejectionEmailTemplateKey, DapAdminRejectionEmailCopy> = {
  practice_enrollment_rejected: {
    templateKey:         'practice_enrollment_rejected',
    audience:            'practice_admin',
    subject:             'Update on your Dental Advantage Plan enrollment request',
    previewText:         'Your DAP enrollment request has been reviewed.',
    headline:            'Practice Enrollment — Not Approved',
    body: [
      'Thank you for your interest in Dental Advantage Plan.',
      'After review, we were unable to approve this enrollment request at this time.',
      'This does not affect your ability to offer dental services or contact your patients directly.',
      'If you have questions or believe this was an error, please contact the Dental Advantage Plan administrator.',
    ],
    footerNote:          DAP_REJECTION_FOOTER_NOTE,
    includesPaymentCta:  false,
    includesPhi:         false,
    includesCta:         false,
  },

  practice_participation_rejected: {
    templateKey:         'practice_participation_rejected',
    audience:            'practice_admin',
    subject:             'Update on your Dental Advantage Plan participation status',
    previewText:         'Your DAP participation status has been reviewed.',
    headline:            'Practice Participation — Not Approved',
    body: [
      'Thank you for your participation in Dental Advantage Plan.',
      'After review, we were unable to continue this practice\'s participation at this time.',
      'Existing patient relationships and appointments are not affected by this notice.',
      'If you have questions, please contact the Dental Advantage Plan administrator.',
    ],
    footerNote:          DAP_REJECTION_FOOTER_NOTE,
    includesPaymentCta:  false,
    includesPhi:         false,
    includesCta:         false,
  },

  member_enrollment_rejected: {
    templateKey:         'member_enrollment_rejected',
    audience:            'member',
    subject:             'Update about your Dental Advantage Plan request',
    previewText:         'Your DAP membership request has been reviewed.',
    headline:            'Membership Request — Not Approved',
    body: [
      'Thank you for your interest in Dental Advantage Plan.',
      'After review, we were unable to approve this membership request at this time.',
      'No payment has been processed by Dental Advantage Plan.',
      'If this was unexpected, please contact your dental practice or the Dental Advantage Plan support team.',
    ],
    footerNote:          DAP_REJECTION_FOOTER_NOTE,
    includesPaymentCta:  false,
    includesPhi:         false,
    includesCta:         false,
  },

  membership_activation_rejected: {
    templateKey:         'membership_activation_rejected',
    audience:            'member',
    subject:             'Update about your Dental Advantage Plan activation',
    previewText:         'Your DAP membership activation has been reviewed.',
    headline:            'Membership Activation — Not Approved',
    body: [
      'Your Dental Advantage Plan membership activation was reviewed.',
      'We were unable to complete the activation at this time.',
      'No payment has been processed by Dental Advantage Plan in connection with this notice.',
      'Please contact your dental practice for next steps.',
    ],
    footerNote:          DAP_REJECTION_FOOTER_NOTE,
    includesPaymentCta:  false,
    includesPhi:         false,
    includesCta:         false,
  },
}

// ─── Accessors ────────────────────────────────────────────────────────────────

export function getDapAdminRejectionEmailCopy(
  templateKey: DapAdminRejectionEmailTemplateKey
): DapAdminRejectionEmailCopy {
  return REJECTION_COPY[templateKey]
}

export function getAllDapAdminRejectionEmailCopy(): DapAdminRejectionEmailCopy[] {
  return Object.values(REJECTION_COPY)
}

// ─── Safety scanner ───────────────────────────────────────────────────────────

function collectCopyText(copy: DapAdminRejectionEmailCopy): string {
  return [copy.subject, copy.headline, copy.previewText, ...copy.body, copy.footerNote]
    .join(' ')
    .toLowerCase()
}

export function isDapAdminRejectionEmailCopySafe(copy: DapAdminRejectionEmailCopy): boolean {
  if (copy.includesPaymentCta !== false) return false
  if (copy.includesPhi !== false) return false
  if (copy.includesCta !== false) return false
  const text = collectCopyText(copy)
  return !DAP_REJECTION_FORBIDDEN_TERMS.some(term => text.includes(term.toLowerCase()))
}

export function assertDapAdminRejectionEmailCopySafe(copy: DapAdminRejectionEmailCopy): void {
  if (copy.includesPaymentCta !== false) {
    throw new Error('Rejection email copy must have includesPaymentCta: false.')
  }
  if (copy.includesPhi !== false) {
    throw new Error('Rejection email copy must have includesPhi: false.')
  }
  if (copy.includesCta !== false) {
    throw new Error('Rejection email copy must have includesCta: false.')
  }
  const text = collectCopyText(copy)
  for (const term of DAP_REJECTION_FORBIDDEN_TERMS) {
    if (text.includes(term.toLowerCase())) {
      throw new Error(`Rejection email copy contains forbidden term: "${term}".`)
    }
  }
}
