// DAP Stage 2 Discovery Audit result.
// Target: https://dentaladvantageplan.vercel.app
// Crawled: 2026-05-03 (17 URLs discovered; 15 content pages, 2 static assets)
// Status: submitted — awaiting owner approval of Stage 2.
//
// Generated by Stage 2 Discovery Agent per agents/dap-stage2-discovery/CLAUDE.md.
// Do not hand-edit audit findings — they must come from the crawler.

import type { DapDiscoveryAuditResult } from './dapDiscoveryAuditTypes'

export type DapDiscoveryAuditStatus = 'not_started' | 'submitted' | 'approved'

export const DAP_DISCOVERY_AUDIT_STATUS: DapDiscoveryAuditStatus = 'submitted'

export const DAP_DISCOVERY_AUDIT: DapDiscoveryAuditResult = {
  auditedAt: '2026-05-03',
  targetBaseUrl: 'https://dentaladvantageplan.vercel.app',
  totalPagesFound: 15,

  // ─── Pages inventory ────────────────────────────────────────────────────────
  // 15 content/utility pages. 2 static asset URLs excluded from inventory.
  // The site has two architecturally distinct versions:
  //   / (root)   — newer cost-comparison homepage
  //   /v5/*      — existing site with legacy path prefix (14 pages)

  pagesInventory: [
    {
      url: 'https://dentaladvantageplan.vercel.app/',
      path: '/',
      statusCode: 200,
      pageTitle: 'Compare Dental Costs Before You Pay Full Price | Dental Advantage Plan',
      h1: 'Before you pay full price for dental care, check if a local membership plan can lower your cost.',
      metaDescription: 'Not insured? See typical retail prices for crowns, root canals, and cleanings — then find participating dentists nearby offering membership pricing. Free to compare.',
      wordCount: 922,
      purpose: 'landing',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      path: '/v5',
      statusCode: 200,
      pageTitle: 'Dental Advantage Plan — Your dentist has a plan, no insurance needed',
      h1: 'Dental care without insurance confusion',
      metaDescription: 'Dental Advantage Plan is an in-house membership you join directly through a participating dentist. Cleanings and exams included. 25% off everything else.',
      wordCount: 837,
      purpose: 'landing',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/search',
      path: '/v5/search',
      statusCode: 200,
      pageTitle: 'Find Affordable Dental Care Near You | Dental Advantage Plan',
      h1: 'Searching...',
      metaDescription: 'Search 3,400+ dental providers — private practices, dental schools, hygiene programs, and residency clinics. Find affordable care in your area.',
      wordCount: 189,
      purpose: 'utility',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/options',
      path: '/v5/options',
      statusCode: 200,
      pageTitle: 'All Options for Dental Care Without Insurance | Dental Advantage Plan',
      h1: 'The Complete Guide to Dental Care Without Insurance',
      metaDescription: 'The complete guide to affordable dental care without insurance. Compare membership plans, discount plans, community health centers, Medicaid, dental schools, and more.',
      wordCount: 1354,
      purpose: 'content',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/calculator',
      path: '/v5/calculator',
      statusCode: 200,
      pageTitle: 'Dental Cost Calculator — What Will You Actually Pay? | Dental Advantage Plan',
      h1: null,
      metaDescription: 'Select the dental procedures you need and instantly see what you\'d pay under every option: membership plans, discount plans, dental schools, and financing.',
      wordCount: 121,
      purpose: 'utility',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/guide',
      path: '/v5/guide',
      statusCode: 200,
      pageTitle: 'The Complete Guide to Dental Care Without Insurance | Dental Advantage Plan',
      h1: 'No Dental Insurance?Here\'s Exactly What to Do.',
      metaDescription: 'No insurance? Here\'s exactly how to get affordable dental care. Step-by-step: membership plans, discount plans, dental schools, cash pricing, and more.',
      wordCount: 697,
      purpose: 'content',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/for-dentists',
      path: '/v5/for-dentists',
      statusCode: 200,
      pageTitle: 'For Dentists | Dental Advantage Plan',
      h1: 'Bring uninsured patientsto your chair.',
      metaDescription: '$49/month gets your practice a DAP listing — your own profile page, a downloadable membership plan PDF, and inbound patient leads in your area. No cut of treatment.',
      wordCount: 531,
      purpose: 'landing',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/find-my-option',
      path: '/v5/find-my-option',
      statusCode: 200,
      pageTitle: 'Dental Advantage Plan | Affordable Dental Care Navigator',
      h1: 'What dental work do you need?',
      metaDescription: 'Free tools to find affordable dental care without insurance. Cost calculator, provider search, and personalized recommendations.',
      wordCount: 155,
      purpose: 'utility',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/quiz',
      path: '/v5/quiz',
      statusCode: 200,
      pageTitle: 'Dental Advantage Plan | Affordable Dental Care Navigator',
      h1: 'What best describes your situation?',
      metaDescription: 'Free tools to find affordable dental care without insurance. Cost calculator, provider search, and personalized recommendations.',
      wordCount: 155,
      purpose: 'utility',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/request-dap',
      path: '/v5/request-dap',
      statusCode: 200,
      pageTitle: 'Request DAP in your area | Dental Advantage Plan',
      h1: 'No DAP dentist in your ZIP yet?',
      metaDescription: 'No Dental Advantage Plan dentist in your ZIP yet? Let us know where you are — we\'ll reach out to dentists in your area and email you when one joins.',
      wordCount: 230,
      purpose: 'utility',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/about',
      path: '/v5/about',
      statusCode: 200,
      pageTitle: 'About | Dental Advantage Plan',
      h1: 'About Dental Advantage Plan',
      metaDescription: 'Dental Advantage Plan helps uninsured patients find dental membership plans at participating practices. Launched in San Diego County.',
      wordCount: 326,
      purpose: 'content',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/contact',
      path: '/v5/contact',
      statusCode: 200,
      pageTitle: 'Contact | Dental Advantage Plan',
      h1: 'Get in touch',
      metaDescription: 'Get in touch with Dental Advantage Plan. Email, mailing address, and links to start a request or apply as a practice.',
      wordCount: 170,
      purpose: 'utility',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/privacy',
      path: '/v5/privacy',
      statusCode: 200,
      pageTitle: 'Privacy Policy | Dental Advantage Plan',
      h1: 'Privacy Policy',
      metaDescription: 'Privacy Policy for Dental Advantage Plan. What we collect, how we use it, and your rights.',
      wordCount: 471,
      purpose: 'utility',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/terms',
      path: '/v5/terms',
      statusCode: 200,
      pageTitle: 'Terms of Service | Dental Advantage Plan',
      h1: 'Terms of Service',
      metaDescription: 'Terms of Service for Dental Advantage Plan. Acceptable use, disclaimers, and limitations.',
      wordCount: 559,
      purpose: 'utility',
      hasStructuredData: false,
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/practice/8c7c6b67-df18-45d3-a6d3-d49ad4789b9b',
      path: '/v5/practice/8c7c6b67-df18-45d3-a6d3-d49ad4789b9b',
      statusCode: 200,
      pageTitle: 'Carmel Mountain Dental Office Stephanie Nguyen DMD — San Diego, CA | Dental Advantage Plan',
      h1: 'Carmel Mountain Dental Office Stephanie Nguyen DMD',
      metaDescription: 'Office details, hours, and contact information for Carmel Mountain Dental Office Stephanie Nguyen DMD in San Diego, CA.',
      wordCount: 316,
      purpose: 'landing',
      hasStructuredData: false,
    },
  ],

  // ─── Copy audit ─────────────────────────────────────────────────────────────
  // Against 7 truth rules and 11 forbidden claims from dapBusinessDefinition.ts.
  // Critical = direct truth rule contradiction. Warning = prohibited phrasing.

  copyAuditFindings: [
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      rule: 'DAP does not set practice pricing (Rule 4) + DAP does not guarantee universal availability (Rule 6)',
      excerpt: 'What you get with DAP — The same coverage framework at every participating practice. Diagnostics 100% covered. Preventive 100% covered. Everything Else 25% off.',
      ruleNumber: 4,
      severity: 'critical',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      rule: 'DAP does not set practice pricing (Rule 4)',
      excerpt: 'DAP practices commit to 25% — roughly double the industry norm. Some practices add extras like ClearCorrect $1,000 off or teeth bleaching $100 off.',
      ruleNumber: 4,
      severity: 'critical',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      rule: 'DAP does not guarantee savings (Rule 5)',
      excerpt: 'Most patients come out ahead—even before major work.',
      ruleNumber: 5,
      severity: 'critical',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      rule: 'DAP does not guarantee savings (Rule 5)',
      excerpt: 'Used by patients who expect real savings—not paperwork.',
      ruleNumber: 5,
      severity: 'warning',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      rule: 'DAP does not set practice pricing (Rule 4)',
      excerpt: 'Crown scenario — DAP ~$900–$1,100 / Insurance $1,200–$1,800.',
      ruleNumber: 4,
      severity: 'warning',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/',
      rule: 'DAP does not guarantee savings (Rule 5)',
      excerpt: 'Most patients come out ahead — even before major work.',
      ruleNumber: 5,
      severity: 'critical',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/',
      rule: 'DAP does not set practice pricing (Rule 4)',
      excerpt: 'Basics + larger treatment — Included care plus a crown or root canal — Plus typical savings (~$200–$500+) — You come out clearly ahead.',
      ruleNumber: 4,
      severity: 'warning',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      rule: 'DAP does not guarantee savings (Rule 5) — meta description states universal discount',
      excerpt: 'Cleanings and exams included. 25% off everything else.',
      ruleNumber: 5,
      severity: 'critical',
    },
  ],

  // ─── CTA audit ──────────────────────────────────────────────────────────────

  ctaFindings: [
    {
      url: 'https://dentaladvantageplan.vercel.app/',
      ctaText: 'Compare My Cost',
      ctaHref: '/v5/calculator',
      classification: 'review_needed',
      reason: 'Implies DAP can calculate an actual member cost — costs are set by each practice, not DAP.',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/',
      ctaText: 'See My Options',
      ctaHref: '/v5/options',
      classification: 'allowed',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      ctaText: 'See your real cost →',
      ctaHref: '/v5/calculator',
      classification: 'review_needed',
      reason: '"Real cost" implies DAP delivers a guaranteed price. Actual pricing is set per practice.',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      ctaText: 'Find a dentist — request DAP there',
      ctaHref: '/v5/search',
      classification: 'allowed',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      ctaText: 'Browse San Diego dentists →',
      ctaHref: '/v5/search',
      classification: 'allowed',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      ctaText: 'Compare 7 care paths →',
      ctaHref: '/v5/options',
      classification: 'allowed',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      ctaText: 'Or take a 2-minute personalized assessment →',
      ctaHref: '/v5/quiz',
      classification: 'allowed',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/for-dentists',
      ctaText: 'Apply to list my practice →',
      ctaHref: '/v5/for-dentists',
      classification: 'allowed',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/request-dap',
      ctaText: 'Request DAP in your area',
      ctaHref: '/v5/request-dap',
      classification: 'allowed',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/search',
      ctaText: 'Find Affordable Dental Care Near You',
      ctaHref: '/v5/search',
      classification: 'allowed',
    },
  ],

  // ─── SEO audit ──────────────────────────────────────────────────────────────
  // No structured data on any page (0/15). Critical gap for LocalBusiness,
  // MedicalBusiness, and FAQPage schema.

  seoAudit: [
    {
      url: 'https://dentaladvantageplan.vercel.app/',
      titleTag: 'Compare Dental Costs Before You Pay Full Price | Dental Advantage Plan',
      titleTagLength: 70,
      metaDescription: 'Not insured? See typical retail prices for crowns, root canals, and cleanings — then find participating dentists nearby offering membership pricing. Free to compare.',
      metaDescriptionLength: 165,
      h1: 'Before you pay full price for dental care, check if a local membership plan can lower your cost.',
      hasStructuredData: false,
      issues: [
        'Title tag 70 chars — exceeds 60-char guideline',
        'Meta description 165 chars — marginally over 160-char guideline',
        'No structured data — Organization or FAQPage schema recommended',
        'H1 is 96 chars and question-form — consider shorter keyword-first H1',
      ],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      titleTag: 'Dental Advantage Plan — Your dentist has a plan, no insurance needed',
      titleTagLength: 68,
      metaDescription: 'Dental Advantage Plan is an in-house membership you join directly through a participating dentist. Cleanings and exams included. 25% off everything else.',
      metaDescriptionLength: 153,
      h1: 'Dental care without insurance confusion',
      hasStructuredData: false,
      issues: [
        'Title tag 68 chars — exceeds 60-char guideline',
        'Meta description contains "25% off everything else" — violates Rule 4 (pricing) and Rule 5 (savings guarantee)',
        'No structured data — Organization schema missing',
        'Duplicate root-level landing page with / — dual landing page creates indexing ambiguity',
      ],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/search',
      titleTag: 'Find Affordable Dental Care Near You | Dental Advantage Plan',
      titleTagLength: 60,
      metaDescription: 'Search 3,400+ dental providers — private practices, dental schools, hygiene programs, and residency clinics. Find affordable care in your area.',
      metaDescriptionLength: 143,
      h1: 'Searching...',
      hasStructuredData: false,
      issues: [
        'H1 is "Searching..." — a JavaScript loading state, not a real heading. Will show in Google as a loading artifact.',
        'Low word count (189) — JS-rendered content is not crawlable by search engines',
        'No structured data',
      ],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/options',
      titleTag: 'All Options for Dental Care Without Insurance | Dental Advantage Plan',
      titleTagLength: 70,
      metaDescription: 'The complete guide to affordable dental care without insurance. Compare membership plans, discount plans, community health centers, Medicaid, dental schools, and more.',
      metaDescriptionLength: 165,
      h1: 'The Complete Guide to Dental Care Without Insurance',
      hasStructuredData: false,
      issues: [
        'Title tag 70 chars — exceeds 60-char guideline',
        'Meta description 165 chars — marginally over 160-char guideline',
        'H1 is identical to /v5/guide title tag — duplicate heading across two pages',
        'No structured data — FAQPage or Article schema recommended for this content',
      ],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/calculator',
      titleTag: 'Dental Cost Calculator — What Will You Actually Pay? | Dental Advantage Plan',
      titleTagLength: 76,
      metaDescription: 'Select the dental procedures you need and instantly see what you\'d pay under every option: membership plans, discount plans, dental schools, and financing.',
      metaDescriptionLength: 153,
      h1: null,
      hasStructuredData: false,
      issues: [
        'Missing H1 — critical SEO issue, no heading for crawlers or screen readers',
        'Title tag 76 chars — exceeds 60-char guideline',
        'Low word count (121) — JS-rendered app, not crawlable',
        'No structured data',
      ],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/guide',
      titleTag: 'The Complete Guide to Dental Care Without Insurance | Dental Advantage Plan',
      titleTagLength: 75,
      metaDescription: 'No insurance? Here\'s exactly how to get affordable dental care. Step-by-step: membership plans, discount plans, dental schools, cash pricing, and more.',
      metaDescriptionLength: 150,
      h1: 'No Dental Insurance?Here\'s Exactly What to Do.',
      hasStructuredData: false,
      issues: [
        'Title tag 75 chars — exceeds 60-char guideline',
        'H1 is missing a space: "No Dental Insurance?Here\'s" — rendering artifact',
        'Title conflicts with /v5/options — both claim to be "The Complete Guide"',
        'No structured data — Article or HowTo schema recommended',
      ],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/for-dentists',
      titleTag: 'For Dentists | Dental Advantage Plan',
      titleTagLength: 36,
      metaDescription: '$49/month gets your practice a DAP listing — your own profile page, a downloadable membership plan PDF, and inbound patient leads in your area. No cut of treatment.',
      metaDescriptionLength: 165,
      h1: 'Bring uninsured patientsto your chair.',
      hasStructuredData: false,
      issues: [
        'H1 is missing a space: "patientsto" — rendering artifact',
        'Meta description 165 chars — marginally over 160-char guideline',
        'Title too short and generic — "For Dentists" misses keywords like "dental membership listing"',
        'No structured data',
      ],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/find-my-option',
      titleTag: 'Dental Advantage Plan | Affordable Dental Care Navigator',
      titleTagLength: 56,
      metaDescription: 'Free tools to find affordable dental care without insurance. Cost calculator, provider search, and personalized recommendations.',
      metaDescriptionLength: 127,
      h1: 'What dental work do you need?',
      hasStructuredData: false,
      issues: [
        'Title identical to /v5/quiz — duplicate title creates indexing conflict',
        'Low word count (155) — JS-rendered',
        'No structured data',
      ],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/quiz',
      titleTag: 'Dental Advantage Plan | Affordable Dental Care Navigator',
      titleTagLength: 56,
      metaDescription: 'Free tools to find affordable dental care without insurance. Cost calculator, provider search, and personalized recommendations.',
      metaDescriptionLength: 127,
      h1: 'What best describes your situation?',
      hasStructuredData: false,
      issues: [
        'Title and meta description identical to /v5/find-my-option — exact duplicate content flags',
        'Low word count (155) — JS-rendered',
        'No structured data',
        'Quiz and find-my-option appear to be the same page at two URLs — canonical tag missing',
      ],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/request-dap',
      titleTag: 'Request DAP in your area | Dental Advantage Plan',
      titleTagLength: 48,
      metaDescription: 'No Dental Advantage Plan dentist in your ZIP yet? Let us know where you are — we\'ll reach out to dentists in your area and email you when one joins.',
      metaDescriptionLength: 149,
      h1: 'No DAP dentist in your ZIP yet?',
      hasStructuredData: false,
      issues: ['No structured data'],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/about',
      titleTag: 'About | Dental Advantage Plan',
      titleTagLength: 29,
      metaDescription: 'Dental Advantage Plan helps uninsured patients find dental membership plans at participating practices. Launched in San Diego County.',
      metaDescriptionLength: 132,
      h1: 'About Dental Advantage Plan',
      hasStructuredData: false,
      issues: [
        'Title "About | Dental Advantage Plan" — too generic, no keyword value',
        'No structured data — Organization schema recommended on About page',
      ],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/contact',
      titleTag: 'Contact | Dental Advantage Plan',
      titleTagLength: 31,
      metaDescription: 'Get in touch with Dental Advantage Plan. Email, mailing address, and links to start a request or apply as a practice.',
      metaDescriptionLength: 117,
      h1: 'Get in touch',
      hasStructuredData: false,
      issues: ['No structured data — ContactPage schema recommended'],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/privacy',
      titleTag: 'Privacy Policy | Dental Advantage Plan',
      titleTagLength: 38,
      metaDescription: 'Privacy Policy for Dental Advantage Plan. What we collect, how we use it, and your rights.',
      metaDescriptionLength: 91,
      h1: 'Privacy Policy',
      hasStructuredData: false,
      issues: [],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/terms',
      titleTag: 'Terms of Service | Dental Advantage Plan',
      titleTagLength: 40,
      metaDescription: 'Terms of Service for Dental Advantage Plan. Acceptable use, disclaimers, and limitations.',
      metaDescriptionLength: 91,
      h1: 'Terms of Service',
      hasStructuredData: false,
      issues: [],
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/practice/8c7c6b67-df18-45d3-a6d3-d49ad4789b9b',
      titleTag: 'Carmel Mountain Dental Office Stephanie Nguyen DMD — San Diego, CA | Dental Advantage Plan',
      titleTagLength: 90,
      metaDescription: 'Office details, hours, and contact information for Carmel Mountain Dental Office Stephanie Nguyen DMD in San Diego, CA.',
      metaDescriptionLength: 118,
      h1: 'Carmel Mountain Dental Office Stephanie Nguyen DMD',
      hasStructuredData: false,
      issues: [
        'Title tag 90 chars — far exceeds 60-char guideline',
        'UUID-based URL (/v5/practice/8c7c6b67-...) — not SEO-friendly, not human-readable',
        'No structured data — LocalBusiness or Dentist schema strongly recommended for practice pages',
        'Will become a broken URL after rebuild unless redirected',
      ],
    },
  ],

  // ─── Design audit notes ─────────────────────────────────────────────────────

  designAuditNotes: [
    {
      url: 'https://dentaladvantageplan.vercel.app/v5',
      issue: 'H1 "Bring uninsured patientsto your chair." contains merged words — missing space, a rendering artifact that will display incorrectly.',
      severity: 'medium',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/for-dentists',
      issue: 'H1 "Bring uninsured patientsto your chair." — same rendering artifact (missing space before "to").',
      severity: 'medium',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/guide',
      issue: 'H1 "No Dental Insurance?Here\'s Exactly What to Do." — missing space after question mark, rendering artifact.',
      severity: 'medium',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/search',
      issue: 'H1 renders as "Searching..." — a JavaScript loading state that is permanently visible to crawlers and screen readers without JS.',
      severity: 'high',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/calculator',
      issue: 'No H1 element present — missing semantic heading landmark.',
      severity: 'high',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/',
      issue: 'Two competing landing pages at / and /v5 — different positioning, different copy. Creates brand inconsistency and duplicate content risk.',
      severity: 'high',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/practice/8c7c6b67-df18-45d3-a6d3-d49ad4789b9b',
      issue: 'Practice pages use opaque UUID URLs — not human-readable, not shareable, not SEO-friendly.',
      severity: 'high',
    },
  ],

  // ─── Broken / stale assets ──────────────────────────────────────────────────

  brokenAssets: [
    {
      url: 'https://dentaladvantageplan.vercel.app/_next/static/chunks/88098d3eb2acb899.css',
      linkedFrom: 'https://dentaladvantageplan.vercel.app/',
      statusCode: 200,
      assetType: 'legacy_route',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/_next/static/chunks/812e2e8e0cbac981.js',
      linkedFrom: 'https://dentaladvantageplan.vercel.app/',
      statusCode: 200,
      assetType: 'legacy_route',
    },
    {
      url: 'https://dentaladvantageplan.vercel.app/v5/practice/8c7c6b67-df18-45d3-a6d3-d49ad4789b9b',
      linkedFrom: 'https://dentaladvantageplan.vercel.app/v5',
      statusCode: 200,
      assetType: 'legacy_route',
    },
  ],

  // ─── Customer-facing change summary ─────────────────────────────────────────

  customerFacingChangeSummary: `The existing site does a good job of educating patients about all dental care options without insurance, but the rebuild will sharpen its focus on finding DAP-participating dentists. Patients will see cleaner, more confident messaging that is clearer about what DAP actually is: a directory connecting you to dentists who offer in-house membership plans — not a plan DAP itself runs. The biggest visible change will be the URL structure: all current pages use a /v5/ prefix (e.g., dentaladvantageplan.com/v5/guide) that will be replaced with clean direct paths (e.g., dentaladvantageplan.com/guide). The calculator and search tools will be rebuilt as server-rendered pages so they are accessible without JavaScript. Practice profile pages will use readable URLs based on practice name and city rather than internal IDs.`,

  agentNotes: `Audit methodology: live crawl of https://dentaladvantageplan.vercel.app (2026-05-03, 17 URLs discovered) + full-text analysis of key pages via server-side fetch. The site has two distinct versions: the root / (newer cost-comparison homepage) and /v5/* (full existing site). dentaladvantageplan.com does not yet have a standalone domain — the site is currently hosted at the Vercel preview URL. The most urgent finding for Stage 3 implications is the /v5 homepage claiming "The same coverage framework at every participating practice" with universal discount rates (25% off) — this directly contradicts Truth Rule 4 (DAP does not set practice pricing) and Rule 5 (DAP does not guarantee savings). This copy must not carry forward into the rebuilt site.`,
}
