// DAP Stage 2 Discovery Audit result.
// Status: not_started — no audit has been run yet.
//
// This file is generated by the Stage 2 Discovery agent.
// To run the agent:
//   TARGET_URL=https://dentaladvantageplan.com claude
// from the repo root, with agents/dap-stage2-discovery/CLAUDE.md loaded.
//
// The agent replaces this file with actual audit findings.
// Do not hand-edit audit findings — they must come from the crawler.

import type { DapDiscoveryAuditResult } from './dapDiscoveryAuditTypes'

export type DapDiscoveryAuditStatus = 'not_started' | 'submitted' | 'approved'

export const DAP_DISCOVERY_AUDIT_STATUS: DapDiscoveryAuditStatus = 'not_started'

export const DAP_DISCOVERY_AUDIT: DapDiscoveryAuditResult | null = null
